import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createTheme, MantineProvider } from "@mantine/core";
import { ModalsProvider } from "@mantine/modals";
import { Notifications } from "@mantine/notifications";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import { TodoProvider } from "@/context/TodoContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  defaultRadius: "md",
  components: {
    Modal: {
      defaultProps: {
        size: "lg",
        centered: true,
      },
      styles: {
        content: {
          backgroundColor: "#111111",
          border: "1px solid #1A202A",
        },
        header: {
          color: "white",
          borderBottom: "1px solid #333",
          backgroundColor: "#111111",
        },
        title: {
          fontSize: "20px",
          fontWeight: 600,
        },
        body: {
          padding: "16px",
        },
      },
    },
    TextInput: {
      styles: {
        label: {
          color: "white",
        },
        input: {
          marginTop: "8px",
          backgroundColor: "#1C1C1C",
          borderColor: "#1A202A",
          color: "white",
        },
      },
    },
    Textarea: {
      styles: {
        label: {
          color: "white",
        },
        input: {
          marginTop: "8px",
          backgroundColor: "#1C1C1C",
          borderColor: "#1A202A",
          color: "white",
        },
      },
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <ModalsProvider>
            <Notifications position="top-center" autoClose={2000} />
            <TodoProvider>{children}</TodoProvider>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
